esports/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
from django.conf.urls.static import static
from django.conf import settings
from django.contrib.auth import views as auth_views

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("eventapp.urls"), name="content"),
    path("accounts/", include("accountapp.urls")),
    path("index/", views.ThanksPage.as_view()),
]
#  path("login/", auth_views.LoginView.as_view(), name="login"),
#     path("logout/", auth_views.LogoutView, name="logout")

if settings.DEBUG:  # new
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

eventapp/urls.py
from django.urls import path
from eventapp import views

app_name = "gallery"

urlpatterns = [
    path("gallery/", views.index, name="gallery"),
    path("post/", views.post, name="eventpost"),
    path("event_detail/<int:id>/", views.event_detail, name="eventdetail"),
    path("upcoming_events/", views.upcoming_events, name="upcoming"),
    path("", views.homePage),
    path("completedevents/", views.completed_events, name="completed"),
    path("delete/<int:id>/", views.deletepost, name="delete"),
    path("eventapp/add_members/<int:id>", views.add_members, name="addmember"),
    path("eventapp/add_member/<int:pid>/<int:mid>", views.add_member, name="addmember"),
    path("postimage/", views.memberimage),
    path("more_events/<str:c>/<int:id>/", views.more_events),
]

templates/completed_events.html
{% extends 'base.html' %}
{% block content %}
<div class="titlebox">
<div class="btn-group">
<a href="{% url 'gallery:upcoming' %}"><div class="upcoming ">Upcoming</div></a>
<a href="{% url 'gallery:completed' %}"><div class="completed">Completed</div></a>
</div>
</div>
<br>



<main>

{% for event in  events %}

<div class=card>
{%if user.is_authenticated%}
  <a class="confirm-delete" href="{% url 'gallery:delete' id=event.id %}"><span class="fa fa-remove"></span></a>
  {%endif%}
    
    <div class="info">
    <strong class='title'>{{event.title}}</strong>
   
    <p id="created_date">{{event.created_date}}</p><br>
    <p class="desc">{{event.description|truncatewords:30}}</p>
    </div>
<div class="contain embed-responsive embed-responsive-16by9">
      {%for img in event.images%}
        <img class ="img embed-responsive-item" src={{img.image.url}} height=500px width=100%>
        {% endfor %}
        <a href="{% url 'gallery:eventdetail' id=event.id %}">
        <div class="middle">
        <div class=text>View Event</div>
        </div>
        </a>

  </div>
  
  </div>


{% endfor %}
</main>

{% endblock content %}

{% block script %}
$(document).on('click', '.confirm-delete', function(){
  {% comment %} alert("Are you sure?") {% endcomment %}
    return confirm('Are you sure you want to delete this?')
});

{% endblock script %}

templates/event_detail.html
{% extends 'base.html' %}
{% block content %}
<div class="container text-white">
<div class="title title-expanded">{{event.title|title}}</div>
<p class=date>{{event.created_date}}</p>
<p class=desc>{{event.description}}</p>
</div>
<main>
 
{% for image in  event.images %}

<div class="gallery">
    

      <a href="{{image.image.url}}" data-toggle="lightbox" data-gallery="example-gallery" data-type="image">
							
        <img class ="img img-fluid img-thumbnail img-responsive" src={{image.thumbnail.url}} height=400px width=100%>
        </a>
  </div>
{% endfor %}
</main>

<div class="members">
{%for images in event.images%}
    <img src={{images.thumbnail.url}}>
    {%endfor%}

</div>

{% endblock content %}
{% block script %}
{% endblock script %}

templates/events.html
{% extends 'base.html' %}
{% block content %}
<div class="titlebox">
<div class="btn-group">
<a href="{% url 'gallery:upcoming' %}"><div class="upcoming ">Upcoming</div></a>
<a href="{% url 'gallery:completed' %}"><div class="completed">Completed</div></a>
</div>
</div>
<br>



<main>

{% for event in  events %}

<div class=card>
{%if user.is_authenticated%}
  <a class="confirm-delete" href="{% url 'gallery:delete' id=event.id %}"><span class="fa fa-remove"></span></a>
  {%endif%}
    
    <div class="info">
    <div class='title'>{{event.title|title}}</div>
   
    <p class="date"><i class="fa fa-calendar" aria-hidden="true"></i>{{event.created_date}}</p>
    <p class="desc">{{event.description|truncatewords:10}}</p>
    </div>
<div class="contain embed-responsive embed-responsive-16by9">
      {%for img in event.images%}
        <img class ="img embed-responsive-item" src={{img.image.url}} height=500px width=100%>
        {% endfor %}
        <a href="{% url 'gallery:eventdetail' id=event.id %}">
        <div class="middle">
        <div class=text>View Event</div>
        </div>
        </a>

  </div>
  
  </div>

{% endfor %}
</main>
<div class=row>
<div class=col-md-4></div>
<div class=col-md-4>
{%if more%}
<a href="/more_events/{{completed}}/{{largest_id}}/">
<button class="btn btn-md form-control mt-2">See More<button>
</a>
{%endif%}
</div>
<div class=col-md-4></div>
</div>

{% endblock content %}
{{% block script %}
$(document).on('click', '.confirm-delete', function(){
  {% comment %} alert("Are you sure?") {% endcomment %}
    return confirm('Are you sure you want to delete this?')
})

{% endblock script %}

templates/footer.html
{% extends 'base.html' %}
{% block footer  %}
<footer id="footer" class="footer-1">
<div class="main-footer widgets-dark typo-light">
<div class="container">
<div class="row">
  
<div class="col-xs-12 col-sm-6 col-md-3">
<div class="widget subscribe no-box">
<h5 class="widget-title">COMPANY NAME<span></span></h5>
<p>About the company, little discription will goes here.. </p>
</div>
</div>

<div class="col-xs-12 col-sm-6 col-md-3">
<div class="widget no-box">
<h5 class="widget-title">Quick Links<span></span></h5>
<ul class="thumbnail-widget">
<li>
<div class="thumb-content"><a href="#.">Get Started</a></div>	
</li>
<li>
<div class="thumb-content"><a href="#.">Top Leaders</a></div>	
</li>
<li>
<div class="thumb-content"><a href="#.">Success Stories</a></div>	
</li>
<li>
<div class="thumb-content"><a href="#.">Event/Tickets</a></div>	
</li>
<li>
<div class="thumb-content"><a href="#.">News</a></div>	
</li>
<li>
<div class="thumb-content"><a href="#.">Lifestyle</a></div>	
</li>
<li>
<div class="thumb-content"><a href="#.">About</a></div>	
</li>
</ul>
</div>
</div>

<div class="col-xs-12 col-sm-6 col-md-3">
<div class="widget no-box">
<h5 class="widget-title">Get Started<span></span></h5>
<p>Get access to your full Training and Marketing Suite.</p>
<a class="btn" href="#." target="_blank">Register Now</a>
</div>
</div>

<div class="col-xs-12 col-sm-6 col-md-3">

<div class="widget no-box">
<h5 class="widget-title">Contact Us<span></span></h5>

<p><a href="mailto:info@domain.com" title="glorythemes">info@domain.com</a></p>
<ul class="social-footer2">
<li class=""><a title="youtube" target="_blank" href="https://www.youtube.com/"><img alt="youtube" width="30" height="30" src=""></a></li>
<li class=""><a title="instagram" target="_blank" href="https://www.instagram.com/"><img alt="instagram" width="30" height="30" src=""></a></li>
</ul>
</div>
</div>

</div>
</div>
</div>
  
<div class="footer-copyright">
<div class="container">
<div class="row">
<div class="col-md-12 text-center">
<p>Copyright Company Name © 2016. All rights reserved.</p>
</div>
</div>
</div>
</div>
</footer>
{% endblock footer %}

templates/gallery.html
{% extends 'base.html' %}    
{% load photo_tags %}
{% block content %}
<div class=gallerycontainer>
<div class=gallery>
	{% if images %}
		{% for image in images %}
			{% with image|split:'.' as strs %}
				{% with strs|length as str_arr_len %}
					{% with str_arr_len|add:'-1' as ext_idx %}
						{% if strs|get_by_index:ext_idx == 'jpg' %}
							<a href="/media/images/{{ image }}">
								<img src="/media/images/{{ image }}" height=400 width=400 alt="{{ image }}">
							</a>
						{% endif %}
					{% endwith %}
				{% endwith %}
			{% endwith %}
			{% if forloop.counter|divisibleby:4 %}
				<div class="clear"></div>
			{% endif %}
		{% endfor %}
	{% else %}
		<p>No image available.</p>
	{% endif %}
	</div>
	</div>

	{% endblock content %} 
	{% block script %}
	<script type='text/javascript'>
		$(document).ready(function() {
			$('.gallery ').simpleLightbox();
		});
	</script>
	{% endblock script %}
 

templates/home.html
<!DOCTYPE html>
{% load staticfiles %}

<html class="no-js">


<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title></title>
    <meta name="description" content="">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
     <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">
</div>
 <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link rel="stylesheet" href="{% static 'css/main.css' %}">
    <link rel="stylesheet" href="https://unpkg.com/swiper/css/swiper.min.css">
    <link rel="stylesheet" href="{% static 'css/footer.css' %}">
    {% comment %} <link rel="stylesheet" href="{% static 'css/gallery.css' %}"> {% endcomment %}

    <link href="https://fonts.googleapis.com/css?family=Manjari|Rubik+Mono+One&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Open+Sans:300|Rajdhani:700&display=swap" rel="stylesheet">
</head>

<body class=text-white id="homepage" data-spy="scroll" data-target=".navbar" data-offset="60">
<style>
.carousel-item {
  height: 100vh;
  min-height: 350px;
  background: no-repeat center center scroll;
  -webkit-background-size: cover;
  -moz-background-size: cover;
  -o-background-size: cover;
  background-size: cover;
    margin-top:0px;
}
    .navbar {
  margin-bottom: 0;
  background-color: #f4511e;
  z-index: 9999;
  border: 0;
  font-size: 12px !important;
  line-height: 1.42857143 !important;
  letter-spacing: 4px;
  border-radius: 0;
}

.navbar li a, .navbar .navbar-brand {
  color: #fff !important;
}

.navbar-nav li a:hover, .navbar-nav li.active a{
  color: #f4511e !important;
  background-color: #fff !important;
}

.navbar-default .navbar-toggle {
  border-color: transparent;
  color: #fff !important;
}


 </style>


<header>
  <div id="carouselExampleIndicators" class="carousel slide" style="position:relative" data-ride="carousel">
    <ol class="carousel-indicators">
      <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
      <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
      <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
    </ol>
    <div class="carousel-inner" role="listbox">
    <nav class="navbar mynavv navbar-default navbar-expand-lg fixed-top">
  <div class="container">
    <a class="navbar-brand" href="#">Start Bootstrap</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
    <div class="collapse navbar-collapse" id="navbarResponsive">
      <ul class="navbar-nav ml-auto">
        <li class="nav-item active">
          <a class="nav-link " href="#home">Home</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#about">About</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#Events">Events</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#team">Team</a>
        </li>
      </ul>
    </div>
    </div>
</nav>
     
      <div class="carousel-item active" style="background-image: url('https://source.unsplash.com/LAaSoL0LrYs/1920x1080')">
        <div class="carousel-caption d-none d-md-block">
          <h2 class="display-4">First Slide</h2>
          <p class="lead imagetext">This is a description for the first slide.</p>
        </div>
      </div>
      <!-- Slide Two - Set the background image for this slide in the line below -->
      <div class="carousel-item" style="background-image: url('https://source.unsplash.com/bF2vsubyHcQ/1920x1080')">
        <div class="carousel-caption d-none d-md-block">
          <h2 class="display-4">Second Slide</h2>
          <p class="lead">This is a description for the second slide.</p>
        </div>
      </div>
      <!-- Slide Three - Set the background image for this slide in the line below -->
      <div class="carousel-item" style="background-image: url('https://source.unsplash.com/szFUQoyvrxM/1920x1080')">
        <div class="carousel-caption d-none d-md-block">
          <h2 class="display-4">Third Slide</h2>
          <p class="lead">This is a description for the third slide.</p>
        </div>
      </div>
    </div>
    <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
          <span class="carousel-control-prev-icon" aria-hidden="true"></span>
          <span class="sr-only">Previous</span>
        </a>
    <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
          <span class="carousel-control-next-icon" aria-hidden="true"></span>
          <span class="sr-only">Next</span>
        </a>
  </div>
</header>

<div class="about jumbotron" id=about >
<strong class=titlemain>ABOUT</strong>
<p >{% lorem 5 %}</p>
<form action="../about" type=get>
<button class="btn btn-primary btn-sm" type=submit>Read More</button>
</div>
</form>
<div class=titlemain>TOP CLIENTS</div>
<div class=close-clients>

</div>
<div  id="Events">
<div class="titlebox">
<div class="btn-group">

<a><div class="upcoming " id="upcoming_events">Upcoming</div></a>
<a><div class="completed" id="completed_events">Completed</div></a>
</div>
</div>
<br>



  <div class=titlemain><h1>EVENTS</h1></div>
<main id=upcoming_events_main>

{% for event in  upcoming_events %}

<div class=card>
{%if user.is_authenticated%}
  <a class="confirm-delete" href="{% url 'gallery:delete' id=event.id %}"><span class="fa fa-remove"></span></a>
  {%endif%}
    
    <div class="info">
    <div class='title'>{{event.title|title}}</div>
   
    <p class="date"><i class="fa fa-calendar" aria-hidden="true"></i>{{event.created_date}}</p>
    <p class="desc">{{event.description|truncatewords:10}}</p>
    </div>
<div class="contain embed-responsive embed-responsive-16by9">
      {%for img in event.images%}
        <img class ="img embed-responsive-item" src={{img.image.url}} height=500px width=100%>
        {% endfor %}
        <a href="{% url 'gallery:eventdetail' id=event.id %}">
        <div class="middle">
        <div class=text>View Event</div>
        </div>
        </a>

  </div>
  
  </div>
</div>

{% endfor %}
<div  id="Events">
</main>
<form action="../upcoming_events/" type=get>
<button class="btn btn-primary btn-sm" type=submit>See More</button>
</form>
</div>

<div id=completed_events_main style="display:none">
<main>

{% for event in  completed_events %}

<div class=card>
{%if user.is_authenticated%}
  <a class="confirm-delete" href="{% url 'gallery:delete' id=event.id %}"><span class="fa fa-remove"></span></a>
  {%endif%}
    
    <div class="info">
    <div class='title'>{{event.title|title}}</div>
   
    <p class="date"><i class="fa fa-calendar" aria-hidden="true"></i>{{event.created_date}}</p>
    <p class="desc">{{event.description|truncatewords:10}}</p>
    </div>
<div class="contain embed-responsive embed-responsive-16by9">
      {%for img in event.images%}
        <img class ="img embed-responsive-item" src={{img.image.url}} height=500px width=100%>
        {% endfor %}
        <a href="{% url 'gallery:eventdetail' id=event.id %}">
        <div class="middle">
        <div class=text>View Event</div>
        </div>
        </a>

  </div>
  
  </div>
  {% endfor %}
    
  </main>
  <form action="../completedevents/" type=get>
<button class="btn btn-primary btn-sm" type=submit>See More</button>
</form>
  </div>

<br><br>
<div class=abou>
<div class=titlemain id=team>OUR TEAM</div>
</div>
<div class=row>
{%for person in team%}
<div class="col-sm-6 col-md-4 col-lg-3">
<div class ="imagecontain">

<img class="img" src={{person.image.url}} style="height:100%;width:100%;object-fit:cover"> 
<a href="/accounts/team_profile/{{person.id}}/"><div class="middle"><p class=text >View Profile</p></div></a>

<div class="profilename">
<div class="name">{{person.first_name}} {{person.last_name}}</div>
<div class= "position">{{person.position}}</div>
</div>
</div>

</div>

{%endfor%}
{%if user.is_authenticated%}
<div class="col-sm-6 col-md-4 col-lg-3">
<div class ="imagecontain">

<img class="img" src="../static/icons/B&Blogo.png" style="height:100%;width:100%;object-fit:cover"> 
<a href="/accounts/add_member_profile/"><div class="middle"><p class=text >Add Member</p></div></a>

</div>
</div>

</div>
{%endif%}
</div>




<br><br>
<div class=titlemain id=videos>VIDEOS</div>
<main>
{%for member in team%}

<div class=card>
<div class=contain>

<iframe width="100%%" height="500"
src="https://www.youtube.com/embed/tgbNymZ7vqY?autoplay=1">
</iframe>
</div> 

</div>
{%endfor%}
</main>
<br>
<form action="../videos" type=get>
<button class="btn btn-primary btn-sm" type=submit>More Videos</button>
</form>
<br><br>
<footer id="footer" class="footer-1">
<div class="main-footer widgets-dark typo-light">
<div class="container">
<div class="row">
  
<div class="col-xs-12 col-sm-6 col-md-3">
<div class="widget subscribe no-box">
<img src="{% static 'icons/B&Blogo.png'%}" height=150px width=150px/>
<h5 class="widget-title">B & B Multimedia<span></span></h5>
<p>About the company, little discription will goes here.. </p>
</div>
</div>

<div class="col-xs-12 col-sm-6 col-md-3">
<div class="widget no-box">
<h5 class="widget-title">Quick Links<span></span></h5>
<ul class="thumbnail-widget">
<li>
<div class="thumb-content"><a href="#.">Events</a></div>	
</li>
<li>
<div class="thumb-content"><a href="#.">Gallery</a></div>	
</li>
<li>
<div class="thumb-content"><a href="#.">Event/Tickets</a></div>	
</li>
<li>
<div class="thumb-content"><a href="#.">News</a></div>	
</li>
<li>
<div class="thumb-content"><a href="#.">Contact</a></div>	
</li>
<li>
<div class="thumb-content"><a href="#.">About</a></div>	
</li>
</ul>
</div>
</div>

<div class="col-xs-12 col-sm-6 col-md-3">
<div class="widget no-box">
<h5 class="widget-title">Get Started<span></span></h5>
<p>Unvail the gaming Experience with us.</p>
<a class="btn" href="#." target="_blank">Search</a>
</div>
</div>

<div class="col-xs-12 col-sm-6 col-md-3">

<div class="widget no-box">
<h5 class="widget-title">Contact Us<span></span></h5>

<p><a href="mailto:info@domain.com" title="glorythemes">info@domain.com</a></p>
<ul class="social-footer2">
<li class=""><a title="youtube" target="_blank" href="https://www.instagram.com/"><img alt="instagram" width="30" height="30" src="{% static 'icons/instagram.svg' %}"></a></li>
<li class=""><a title="instagram" target="_blank" href="https://www.facebook.com/"><img alt="facebook" width="30" height="30" src="{% static 'icons/facebook.svg' %}"></a></li>
<li class=""><a title="youtube" target="_blank" href="https://www.youtube.com/"><img alt="youtube" width="30" height="30" src="{% static 'icons/youtube.svg' %}"></a></li>
<li class=""><a title="instagram" target="_blank" href="https://www.instagram.com/"><img alt="twitter" width="30" height="30" src="{% static 'icons/twitter.svg' %}"></a></li>
<li class=""><a title="youtube" target="_blank" href="https://www.linkedin.com/"><img alt="linkedin" width="30" height="30" src="{% static 'icons/linkedin.svg' %}"></a></li>
<li class=""><a title="instagram" target="_blank" href="https://www.googleplus.com/"><img alt="googleplus" width="30" height="30" src="{% static 'icons/google-plus.svg' %}"></a></li>
<li>
</li>
</ul>
</div>
</div>

</div>
</div>
</div>
  
<div class="footer-copyright">
<div class="container">
<div class="row">
<div class="col-md-12 text-center">
<p>Copyright B&B Multimedia © 2019. All rights reserved.</p>
</div>
</div>
</div>
</div>
</footer>

   
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.2.4/jquery.min.js"></script>
    <script src="{% static 'js/bootstrap.min.js' %}" async defer></script>
    <script src="https://unpkg.com/swiper/js/swiper.min.js"></script>
 <script>
$(document).ready(function(){
  $(".upcoming").css({"backgroundColor":"#ff8d1e","color":"white"});
});
</script>
<script>
 $(".upcoming").click(function(e){
     
         $("#upcoming_events_main").css("display","block");
         $("#completed_events_main").css("display","none");
         $(".completed").css({"backgroundColor":"","color":"#ff8d1e"});
         $(".upcoming").css({"backgroundColor":"#ff8d1e","color":"white"});
         
 })
     $(".completed").click(function(e){
         $(".upcoming").css({"backgroundColor":"","color":"#ff8d1e"});
         $(".completed").css({"backgroundColor":"#ff8d1e","color":"white"});
         $("#upcoming_events_main").css("display","none");
         $("#completed_events_main").css("display","block");
     
   
    
 });
//  $(window).scroll(function() {
//     if ($(window).scrollTop() >= 500) { // this refers to window
//        $("nav").css("backgroundColor","white"); 
//     }
// });
var activeNavItem = $('.nav-item');

activeNavItem.click(function(){
  activeNavItem.removeClass('active');
  $(this).addClass('active');  
});
 </script>   
 <script>
 

 {% comment %} $(window).scroll(function() {
  
    if ($(window).scrollTop() >= 500) { 
    
       $("nav").css("backgroundColor","white"); 

  
    }
    
     else if ($(window).scrollTop() < 500) { 
    
       $("nav").css("backgroundColor","none"); 

  
    }
}); {% endcomment %}


 



    
     

 </script>

</body>

</html>

templates/postimage.html
{% extends 'base.html' %}
{% block content %}
<form class=text-white id="post_form" method="post" action="/completedevents/" enctype="multipart/form-data">
{% csrf_token %}
<br><div class="container">
  <div class="row">
  <div class="col-sm-2 imgUp">
    <div class="imagePreview"></div>
<label class="btn btn-primary">
										    			Upload<input type="file" name="personimage" class="uploadFile img" value="Upload Photo" style="width: 0px;height: 0px;overflow: hidden;">
				</label>
  </div><!-- col-2 -->
 
 </div><!-- row -->
</div><!-- container -->
 <button type="submit" class="btn btn-success">
    <i class="fa fa-arrow-circle-right fa-lg"></i>
</button>
</form>
{% endblock content %}


{% block script %}
$(".imgAdd").click(function(){
  $(this).closest(".row").find('.imgAdd').before('<div class="col-sm-2 imgUp"><div class="imagePreview"></div><label class="btn btn-primary">Upload<input type="file" class="uploadFile img" value="Upload Photo" style="width:0px;height:0px;overflow:hidden;"></label><i class="fa fa-times del"></i></div>');
});
$(document).on("click", "i.del" , function() {
	$(this).parent().remove();
});
$(function() {
    $(document).on("change",".uploadFile", function()
    {
    		var uploadFile = $(this);
        var files = !!this.files ? this.files : [];
        if (!files.length || !window.FileReader) return; // no file selected, or no FileReader support
 
        if (/^image/.test( files[0].type)){ // only image file
            var reader = new FileReader(); // instance of the FileReader
            reader.readAsDataURL(files[0]); // read the local file
 
            reader.onloadend = function(){ // set image data as background of div
                //alert(uploadFile.closest(".upimage").find('.imagePreview').length);
uploadFile.closest(".imgUp").find('.imagePreview').css("background-image", "url("+this.result+")");
            }
        }
      
    });
});

{% endblock script %}

templates/upcoming_events.html
{% extends 'base.html' %}
<div class="titlebox">
<div class="btn-group">
<a href="{% url 'gallery:upcoming' %}"><div class="upcoming ">Upcoming</div></a>
<a href="{% url 'gallery:completed' %}"><div class="completed">Completed</div></a>
</div>
</div>
<br>



<main>

{% for event in  events %}

<div class=card>
{%if user.is_authenticated%}
  <a class="confirm-delete" href="{% url 'gallery:delete' id=event.id %}" ...>Delete</a>
  {%endif%}
    
    <div class="info">
    <strong class='title'>{{event.title}}</strong>
   
    <p id="created_date">{{event.created_date}}</p><br>
    <p class="desc">{{event.description|truncatewords:50}}</p>
    </div>
<div class=contain>
      {%for img in event.images%}
        <img class ="img" src={{img.image.url}} height=500px width=100%>
        {% endfor %}
        <a href="{% url 'gallery:eventdetail' id=event.id %}">
        <div class="middle">
        <div class=text>View Event</div>
        </div>
        </a>

  </div>
  
  </div>

{% endfor %}
</main>
{{% block script %}
$(document).on('click', '.confirm-delete', function(){
  {% comment %} alert("Are you sure?") {% endcomment %}
    return confirm('Are you sure you want to delete this?')
})

{% endblock script %}